### ISSUE TITLE
[meta] The road to 1.0

### ISSUE THREAD

**Issue by dunglas** [api-platform/api-platform#9]
The roadmap:

DunglasApiBundle:

1. [ ] Improve the quality (fix issues raised by Scrutinizr https://scrutinizer-ci.com/g/dunglas/DunglasApiBundle/ a notation > 9/10 is the goal)
2. [ ] Increase the unit test coverage (both in DunglasApiBundle, > 80% is the goal), needed for php-schema too. Existing unit tests must also be refactored: external libraries must not ne mocked anymore and value objects must be used directly, not mocked.
3. [x] Implement the ADR pattern instead of current controllers dunglas/DunglasApiBundle#191
4. [x] Decouple from Hydra dunglas/DunglasApiBundle#191
5. [ ] Rename `Resource` to `ResourceType` and make it immutable as done for metadata (dunglas/DunglasApiBundle#180). As they are value object, their interface can be removed.
6. [ ] Enhance the configuration system: create a `@Resource` and `@Operation` annotation
7. [ ] Isolate the Symfony related code (the bundle class, the configuration and dependency injection related code) to make api platform an isolated library (but still usable easily with Symfony)
8. [ ] Last but not least, move every repositories to the org https://github.com/api-platform and change namespace of all projects from `Dunglas` to `ApiPlatform`

The renaming will be:

* [ ] dunglas/api-platform-doc -> api-platform/doc
* [ ] dunglas/DunglasApiBundle -> api-platform/core / ApiPlatform\Core
* [ ] dunglas/php-schema -> api-platform/schema-generator ApiPlatform\SchemaGenerator
* [ ] dunglas/php-property-info -> api-platform/property-info ApiPlatform\PropertyInfo
* [ ] dunglas/api-platform-heroku -> api-platform/heroku-integration ApiPlatform\Heroku
* [ ] dunglas/blog-api -> api-platform/demo-blog-api
* [ ] dunglas/blog-client -> api-platform/demo-blog-client-angular
* [ ] (maybe, I need to think more about that) dunglas/DunglasAngularCsrfBundle -> api-platform/ApiPlatformSpaCsrfBundle / ApiPlatform\Bundle\SpaCsrf

Maybe can we integrate @theofidry's https://github.com/theofidry/LoopBackApiBundle and @vincentchalamon's https://github.com/vincentchalamon/docker-symfony under the api-platform org too

Some non-coding tasks are also in progress:
* [ ] a dedicated website (the web design is done, it must be integrated and developed using https://github.com/dunglas/calavera)
* [ ] more doc: https://github.com/dunglas/api-platform-doc / https://github.com/dunglas/DunglasApiBundle/tree/master/Resources/doc / https://github.com/dunglas/php-schema/tree/master/doc

Our focus is currently on ApiBundle, some architecture changes are in progress: https://github.com/dunglas/DunglasApiBundle/issues
